/*
 * ManeuverRateCascadeParams.h
 *
 *  Created on: Oct 12, 2019
 *      Author: mirco
 */

#ifndef UAVAP_FLIGHTCONTROL_CONTROLLER_PIDCONTROLLER_MANEUVERRATEPIDCONTROLLER_MANEUVERRATECASCADEPARAMS_H_
#define UAVAP_FLIGHTCONTROL_CONTROLLER_PIDCONTROLLER_MANEUVERRATEPIDCONTROLLER_MANEUVERRATECASCADEPARAMS_H_



struct ManeuverRateCascadeParams
{
	template <typename Config>
	void
	configure(Config& c)
	{

	}
};

#endif /* UAVAP_FLIGHTCONTROL_CONTROLLER_PIDCONTROLLER_MANEUVERRATEPIDCONTROLLER_MANEUVERRATECASCADEPARAMS_H_ */
