// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attitudes.proto

#ifndef PROTOBUF_INCLUDED_Attitudes_2eproto
#define PROTOBUF_INCLUDED_Attitudes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Attitudes_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Attitudes_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Attitudes_2eproto();
class AttitudeEuler;
class AttitudeEulerDefaultTypeInternal;
extern AttitudeEulerDefaultTypeInternal _AttitudeEuler_default_instance_;
namespace google {
namespace protobuf {
template<> ::AttitudeEuler* Arena::CreateMaybeMessage<::AttitudeEuler>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class AttitudeEuler : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AttitudeEuler) */ {
 public:
  AttitudeEuler();
  virtual ~AttitudeEuler();

  AttitudeEuler(const AttitudeEuler& from);

  inline AttitudeEuler& operator=(const AttitudeEuler& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AttitudeEuler(AttitudeEuler&& from) noexcept
    : AttitudeEuler() {
    *this = ::std::move(from);
  }

  inline AttitudeEuler& operator=(AttitudeEuler&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AttitudeEuler& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AttitudeEuler* internal_default_instance() {
    return reinterpret_cast<const AttitudeEuler*>(
               &_AttitudeEuler_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AttitudeEuler* other);
  friend void swap(AttitudeEuler& a, AttitudeEuler& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AttitudeEuler* New() const final {
    return CreateMaybeMessage<AttitudeEuler>(NULL);
  }

  AttitudeEuler* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AttitudeEuler>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AttitudeEuler& from);
  void MergeFrom(const AttitudeEuler& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AttitudeEuler* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double roll = 1;
  void clear_roll();
  static const int kRollFieldNumber = 1;
  double roll() const;
  void set_roll(double value);

  // double pitch = 2;
  void clear_pitch();
  static const int kPitchFieldNumber = 2;
  double pitch() const;
  void set_pitch(double value);

  // double yaw = 3;
  void clear_yaw();
  static const int kYawFieldNumber = 3;
  double yaw() const;
  void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:AttitudeEuler)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double roll_;
  double pitch_;
  double yaw_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Attitudes_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AttitudeEuler

// double roll = 1;
inline void AttitudeEuler::clear_roll() {
  roll_ = 0;
}
inline double AttitudeEuler::roll() const {
  // @@protoc_insertion_point(field_get:AttitudeEuler.roll)
  return roll_;
}
inline void AttitudeEuler::set_roll(double value) {
  
  roll_ = value;
  // @@protoc_insertion_point(field_set:AttitudeEuler.roll)
}

// double pitch = 2;
inline void AttitudeEuler::clear_pitch() {
  pitch_ = 0;
}
inline double AttitudeEuler::pitch() const {
  // @@protoc_insertion_point(field_get:AttitudeEuler.pitch)
  return pitch_;
}
inline void AttitudeEuler::set_pitch(double value) {
  
  pitch_ = value;
  // @@protoc_insertion_point(field_set:AttitudeEuler.pitch)
}

// double yaw = 3;
inline void AttitudeEuler::clear_yaw() {
  yaw_ = 0;
}
inline double AttitudeEuler::yaw() const {
  // @@protoc_insertion_point(field_get:AttitudeEuler.yaw)
  return yaw_;
}
inline void AttitudeEuler::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:AttitudeEuler.yaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Attitudes_2eproto
