// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shapes.proto

#include "Shapes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_Positions_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PositionENU_Positions_2eproto;
class RectanguloidDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Rectanguloid> _instance;
} _Rectanguloid_default_instance_;
static void InitDefaultsRectanguloid_Shapes_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Rectanguloid_default_instance_;
    new (ptr) ::Rectanguloid();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Rectanguloid::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Rectanguloid_Shapes_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsRectanguloid_Shapes_2eproto}, {
      &scc_info_PositionENU_Positions_2eproto.base,}};

void InitDefaults_Shapes_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_Rectanguloid_Shapes_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_Shapes_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_Shapes_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_Shapes_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_Shapes_2eproto::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, center_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, major_side_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, minor_side_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, major_side_orientation_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Rectanguloid, height_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Rectanguloid)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Rectanguloid_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_Shapes_2eproto = {
  {}, AddDescriptors_Shapes_2eproto, "Shapes.proto", schemas,
  file_default_instances, TableStruct_Shapes_2eproto::offsets,
  file_level_metadata_Shapes_2eproto, 1, file_level_enum_descriptors_Shapes_2eproto, file_level_service_descriptors_Shapes_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_Shapes_2eproto = {
  false, InitDefaults_Shapes_2eproto, 
  "\n\014Shapes.proto\032\017Positions.proto\"\222\001\n\014Rect"
  "anguloid\022\034\n\006center\030\001 \001(\0132\014.PositionENU\022\031"
  "\n\021major_side_length\030\002 \001(\001\022\031\n\021minor_side_"
  "length\030\003 \001(\001\022\036\n\026major_side_orientation\030\004"
  " \001(\001\022\016\n\006height\030\005 \001(\001b\006proto3"
,
  "Shapes.proto", &assign_descriptors_table_Shapes_2eproto, 188,
};

void AddDescriptors_Shapes_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_Positions_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_Shapes_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Shapes_2eproto = []() { AddDescriptors_Shapes_2eproto(); return true; }();

// ===================================================================

void Rectanguloid::InitAsDefaultInstance() {
  ::_Rectanguloid_default_instance_._instance.get_mutable()->center_ = const_cast< ::PositionENU*>(
      ::PositionENU::internal_default_instance());
}
class Rectanguloid::HasBitSetters {
 public:
  static const ::PositionENU& center(const Rectanguloid* msg);
};

const ::PositionENU&
Rectanguloid::HasBitSetters::center(const Rectanguloid* msg) {
  return *msg->center_;
}
void Rectanguloid::clear_center() {
  if (GetArenaNoVirtual() == NULL && center_ != NULL) {
    delete center_;
  }
  center_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Rectanguloid::kCenterFieldNumber;
const int Rectanguloid::kMajorSideLengthFieldNumber;
const int Rectanguloid::kMinorSideLengthFieldNumber;
const int Rectanguloid::kMajorSideOrientationFieldNumber;
const int Rectanguloid::kHeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Rectanguloid::Rectanguloid()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Rectanguloid)
}
Rectanguloid::Rectanguloid(const Rectanguloid& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_center()) {
    center_ = new ::PositionENU(*from.center_);
  } else {
    center_ = NULL;
  }
  ::memcpy(&major_side_length_, &from.major_side_length_,
    static_cast<size_t>(reinterpret_cast<char*>(&height_) -
    reinterpret_cast<char*>(&major_side_length_)) + sizeof(height_));
  // @@protoc_insertion_point(copy_constructor:Rectanguloid)
}

void Rectanguloid::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Rectanguloid_Shapes_2eproto.base);
  ::memset(&center_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&center_)) + sizeof(height_));
}

Rectanguloid::~Rectanguloid() {
  // @@protoc_insertion_point(destructor:Rectanguloid)
  SharedDtor();
}

void Rectanguloid::SharedDtor() {
  if (this != internal_default_instance()) delete center_;
}

void Rectanguloid::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Rectanguloid& Rectanguloid::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Rectanguloid_Shapes_2eproto.base);
  return *internal_default_instance();
}


void Rectanguloid::Clear() {
// @@protoc_insertion_point(message_clear_start:Rectanguloid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && center_ != NULL) {
    delete center_;
  }
  center_ = NULL;
  ::memset(&major_side_length_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&major_side_length_)) + sizeof(height_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Rectanguloid::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Rectanguloid*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    if (!ptr) goto error;
    switch (tag >> 3) {
      case 0: goto error;
      // .PositionENU center = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        if (!ptr) goto error;
        parser_till_end = ::PositionENU::_InternalParse;
        object = msg->mutable_center();
        if (size > end - ptr) goto len_delim_till_end;
        auto newend = ptr + size;
        if (!ctx->ParseExactRange({parser_till_end, object}, ptr, newend)) goto error;
        ptr = newend;
        break;
      }
      // double major_side_length = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 17) goto handle_unusual;
        double val;
        ::std::memcpy(&val, ptr, 8);
        ptr += 8;
        msg->set_major_side_length(val);
        break;
      }
      // double minor_side_length = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 25) goto handle_unusual;
        double val;
        ::std::memcpy(&val, ptr, 8);
        ptr += 8;
        msg->set_minor_side_length(val);
        break;
      }
      // double major_side_orientation = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 33) goto handle_unusual;
        double val;
        ::std::memcpy(&val, ptr, 8);
        ptr += 8;
        msg->set_major_side_orientation(val);
        break;
      }
      // double height = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 41) goto handle_unusual;
        double val;
        ::std::memcpy(&val, ptr, 8);
        ptr += 8;
        msg->set_height(val);
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4) {
          if (!ctx->ValidEndGroup(tag)) goto error;
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
error:
  return nullptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Rectanguloid::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Rectanguloid)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .PositionENU center = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_center()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double major_side_length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (17 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &major_side_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double minor_side_length = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (25 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &minor_side_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double major_side_orientation = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (33 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &major_side_orientation_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double height = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (41 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Rectanguloid)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Rectanguloid)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Rectanguloid::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Rectanguloid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .PositionENU center = 1;
  if (this->has_center()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::center(this), output);
  }

  // double major_side_length = 2;
  if (this->major_side_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->major_side_length(), output);
  }

  // double minor_side_length = 3;
  if (this->minor_side_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->minor_side_length(), output);
  }

  // double major_side_orientation = 4;
  if (this->major_side_orientation() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->major_side_orientation(), output);
  }

  // double height = 5;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->height(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Rectanguloid)
}

::google::protobuf::uint8* Rectanguloid::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Rectanguloid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .PositionENU center = 1;
  if (this->has_center()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::center(this), deterministic, target);
  }

  // double major_side_length = 2;
  if (this->major_side_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->major_side_length(), target);
  }

  // double minor_side_length = 3;
  if (this->minor_side_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->minor_side_length(), target);
  }

  // double major_side_orientation = 4;
  if (this->major_side_orientation() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->major_side_orientation(), target);
  }

  // double height = 5;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->height(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Rectanguloid)
  return target;
}

size_t Rectanguloid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Rectanguloid)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .PositionENU center = 1;
  if (this->has_center()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *center_);
  }

  // double major_side_length = 2;
  if (this->major_side_length() != 0) {
    total_size += 1 + 8;
  }

  // double minor_side_length = 3;
  if (this->minor_side_length() != 0) {
    total_size += 1 + 8;
  }

  // double major_side_orientation = 4;
  if (this->major_side_orientation() != 0) {
    total_size += 1 + 8;
  }

  // double height = 5;
  if (this->height() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Rectanguloid::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Rectanguloid)
  GOOGLE_DCHECK_NE(&from, this);
  const Rectanguloid* source =
      ::google::protobuf::DynamicCastToGenerated<Rectanguloid>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Rectanguloid)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Rectanguloid)
    MergeFrom(*source);
  }
}

void Rectanguloid::MergeFrom(const Rectanguloid& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Rectanguloid)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_center()) {
    mutable_center()->::PositionENU::MergeFrom(from.center());
  }
  if (from.major_side_length() != 0) {
    set_major_side_length(from.major_side_length());
  }
  if (from.minor_side_length() != 0) {
    set_minor_side_length(from.minor_side_length());
  }
  if (from.major_side_orientation() != 0) {
    set_major_side_orientation(from.major_side_orientation());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
}

void Rectanguloid::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Rectanguloid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Rectanguloid::CopyFrom(const Rectanguloid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Rectanguloid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Rectanguloid::IsInitialized() const {
  return true;
}

void Rectanguloid::Swap(Rectanguloid* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Rectanguloid::InternalSwap(Rectanguloid* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(center_, other->center_);
  swap(major_side_length_, other->major_side_length_);
  swap(minor_side_length_, other->minor_side_length_);
  swap(major_side_orientation_, other->major_side_orientation_);
  swap(height_, other->height_);
}

::google::protobuf::Metadata Rectanguloid::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Shapes_2eproto);
  return ::file_level_metadata_Shapes_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Rectanguloid* Arena::CreateMaybeMessage< ::Rectanguloid >(Arena* arena) {
  return Arena::CreateInternal< ::Rectanguloid >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
